rules_folder: rules
run_every:
  seconds: 10
buffer_time:
  minutes: 15
es_host: {{ES_HOST}}
es_port: {{ES_PORT}}
use_ssl: {{USE_SSL}}
verify_certs: {{VERIFY_CERTS}}
es_username: {{ES_USERNAME}}
es_password: {{ES_PASSWORD}}
writeback_index: elastalert_status
alert_time_limit:
  days: 2
