rules_folder: rules
run_every:
  seconds: 10
buffer_time:
  minutes: 15
es_host: 192.168.26.239
es_port: 9200
use_ssl: false
verify_certs: False
es_username: elastic
es_password: elastic
writeback_index: elastalert_status
alert_time_limit:
  days: 2
