apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastalert-deployment
  labels:
    app: elastalert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastalert
  template:
    metadata:
      labels:
        app: elastalert
    spec:
      containers:
      - name: elastalert
        image: elastalert:latest
        ports:
        - containerPort: 3030
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.yaml
          subPath: config.yaml
        - name: rules-volume
          mountPath: /app/rules
      volumes:
      - name: config-volume
        configMap:
          name: elastalert-config
      - name: rules-volume
        configMap:
          name: elastalert-rules
